package com.doan.backend.common.enums;

public enum MenuDetail {
    GOI_Y_HOM_NAY,
    GAN_BAN,
    DANG_MO_CUA,
    BUN_PHO,
    COM,
    BANH_MI,
    CHAO,
    MI_MIEN,
    LAU,
    HAI_SAN,
    NUONG,
    LAU_NHAU,
    BIA_HOI,
    MOI_NHAU,
    TRA_SUA,
    NUOC_EP,
    SINH_TO,
    TRA_TRAI_CAY,
    DO_UONG_HEALTHY,
    CAFE_TRUYEN_THONG,
    CAFE_MAY,
    COLD_BREW,
    CAFE_HOC_TAP_LAM_VIEC,
    CAFE_SAN_VUON,
    BANH_NGOT,
    BANH_TRANG,
    XIEN_QUE,
    CHE,
    KEM,
    AN_VAT_HAN_QUOC
}
