ALTER TABLE tblquanan ADD COLUMN IF NOT EXISTS hinhanh VARCHAR(1000);
ALTER TABLE tblquanan ADD COLUMN IF NOT EXISTS image_public_id VARCHAR(255);

ALTER TABLE tblmenu ADD COLUMN IF NOT EXISTS hinhanh VARCHAR(1000);
ALTER TABLE tblmenu ADD COLUMN IF NOT EXISTS image_public_id VARCHAR(255);
